
require(devtools)
require(rCharts)
require(stats4)
require(scales)
require(adegenet)
require(hexbin)
require(RColorBrewer)
require(OmicCircos)
require(fields)
require(shiny)
setwd("inst/mainserver")
runApp()
