// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// C_harmonicDist
Rcpp::List C_harmonicDist(std::vector< std::vector<double> > data);
RcppExport SEXP MINOTAUR_C_harmonicDist(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector< std::vector<double> > >::type data(dataSEXP);
    __result = Rcpp::wrap(C_harmonicDist(data));
    return __result;
END_RCPP
}
// C_kernelDist
Rcpp::List C_kernelDist(std::vector< std::vector<double> > data, double sigma2);
RcppExport SEXP MINOTAUR_C_kernelDist(SEXP dataSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector< std::vector<double> > >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    __result = Rcpp::wrap(C_kernelDist(data, sigma2));
    return __result;
END_RCPP
}
// C_kernelLogLike
Rcpp::List C_kernelLogLike(std::vector< std::vector<double> > data, double sigma2);
RcppExport SEXP MINOTAUR_C_kernelLogLike(SEXP dataSEXP, SEXP sigma2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector< std::vector<double> > >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    __result = Rcpp::wrap(C_kernelLogLike(data, sigma2));
    return __result;
END_RCPP
}
// C_neighborDist
Rcpp::List C_neighborDist(std::vector< std::vector<double> > data);
RcppExport SEXP MINOTAUR_C_neighborDist(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector< std::vector<double> > >::type data(dataSEXP);
    __result = Rcpp::wrap(C_neighborDist(data));
    return __result;
END_RCPP
}
