# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_harmonicDist <- function(data) {
    .Call('MINOTAUR_C_harmonicDist', PACKAGE = 'MINOTAUR', data)
}

C_harmonicDist2 <- function(data, S_inv) {
    .Call('MINOTAUR_C_harmonicDist2', PACKAGE = 'MINOTAUR', data, S_inv)
}

C_kernelDeviance <- function(data, sigma2) {
    .Call('MINOTAUR_C_kernelDeviance', PACKAGE = 'MINOTAUR', data, sigma2)
}

C_kernelDeviance2 <- function(data, sigma2, S_inv) {
    .Call('MINOTAUR_C_kernelDeviance2', PACKAGE = 'MINOTAUR', data, sigma2, S_inv)
}

C_kernelDist <- function(data, sigma2) {
    .Call('MINOTAUR_C_kernelDist', PACKAGE = 'MINOTAUR', data, sigma2)
}

C_kernelDist2 <- function(data, sigma2, S_inv) {
    .Call('MINOTAUR_C_kernelDist2', PACKAGE = 'MINOTAUR', data, sigma2, S_inv)
}

C_neighborDist <- function(data) {
    .Call('MINOTAUR_C_neighborDist', PACKAGE = 'MINOTAUR', data)
}

C_neighborDist2 <- function(data, S_inv) {
    .Call('MINOTAUR_C_neighborDist2', PACKAGE = 'MINOTAUR', data, S_inv)
}

